package QuizSystem.otherUI;

import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author trant
 */
public class SingleChoice extends javax.swing.JPanel {

    /**
     * Creates new form Dip
     */
    private JRadioButton[] rdos;

    public SingleChoice() {
        initComponents();
        rdos = new JRadioButton[]{rdo1, rdo2, rdo3, rdo4};
    }

    public JRadioButton[] getRdos() {
        return rdos;
    }

    public void setRdos(JRadioButton[] rdos) {
        this.rdos = rdos;
    }

    public JRadioButton getRdo1() {
        return rdo1;
    }

    public void setRdo1(JRadioButton rdo1) {
        this.rdo1 = rdo1;
    }

    public JRadioButton getRdo2() {
        return rdo2;
    }

    public void setRdo2(JRadioButton rdo2) {
        this.rdo2 = rdo2;
    }

    public JRadioButton getRdo3() {
        return rdo3;
    }

    public void setRdo3(JRadioButton rdo3) {
        this.rdo3 = rdo3;
    }

    public JRadioButton getRdo4() {
        return rdo4;
    }

    public void setRdo4(JRadioButton rdo4) {
        this.rdo4 = rdo4;
    }

    public JLabel getLbImage() {
        return lbImage;
    }

    public void setLbImage(JLabel lbImage) {
        this.lbImage = lbImage;
    }

    public JTextArea getTxtaQuestion() {
        return txtaQuestion;
    }

    public void setTxtaQuestion(JTextArea txtaQuestion) {
        this.txtaQuestion = txtaQuestion;
    }

    public String getSelected() {
        for (JRadioButton rdo : rdos) {
            if (rdo.isSelected()) return rdo.getText();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelQuestion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaQuestion = new javax.swing.JTextArea();
        lbImage = new javax.swing.JLabel();
        panelAnswer = new javax.swing.JPanel();
        rdo1 = new javax.swing.JRadioButton();
        rdo2 = new javax.swing.JRadioButton();
        rdo3 = new javax.swing.JRadioButton();
        rdo4 = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(738, 360));
        setLayout(new java.awt.GridLayout(2, 1));

        jScrollPane2.setBorder(null);

        txtaQuestion.setEditable(false);
        txtaQuestion.setBackground(new java.awt.Color(214, 217, 223));
        txtaQuestion.setColumns(20);
        txtaQuestion.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        txtaQuestion.setLineWrap(true);
        txtaQuestion.setRows(1);
        txtaQuestion.setBorder(null);
        jScrollPane2.setViewportView(txtaQuestion);

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setOpaque(true);

        javax.swing.GroupLayout panelQuestionLayout = new javax.swing.GroupLayout(panelQuestion);
        panelQuestion.setLayout(panelQuestionLayout);
        panelQuestionLayout.setHorizontalGroup(
            panelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelQuestionLayout.setVerticalGroup(
            panelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelQuestion);

        buttonGroup1.add(rdo1);
        rdo1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        rdo1.setToolTipText("");

        buttonGroup1.add(rdo2);
        rdo2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        rdo2.setToolTipText("");

        buttonGroup1.add(rdo3);
        rdo3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        rdo3.setToolTipText("");

        buttonGroup1.add(rdo4);
        rdo4.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        rdo4.setToolTipText("");

        javax.swing.GroupLayout panelAnswerLayout = new javax.swing.GroupLayout(panelAnswer);
        panelAnswer.setLayout(panelAnswerLayout);
        panelAnswerLayout.setHorizontalGroup(
            panelAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo1)
                    .addComponent(rdo2)
                    .addComponent(rdo3)
                    .addComponent(rdo4))
                .addContainerGap(715, Short.MAX_VALUE))
        );
        panelAnswerLayout.setVerticalGroup(
            panelAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdo1)
                .addGap(18, 18, 18)
                .addComponent(rdo2)
                .addGap(18, 18, 18)
                .addComponent(rdo3)
                .addGap(18, 18, 18)
                .addComponent(rdo4)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(panelAnswer);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbImage;
    private javax.swing.JPanel panelAnswer;
    private javax.swing.JPanel panelQuestion;
    private javax.swing.JRadioButton rdo1;
    private javax.swing.JRadioButton rdo2;
    private javax.swing.JRadioButton rdo3;
    private javax.swing.JRadioButton rdo4;
    private javax.swing.JTextArea txtaQuestion;
    // End of variables declaration//GEN-END:variables
}
