/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package QuizSystem.ui;

import QuizSystem.dao.ExamDAO;
import QuizSystem.otherUI.ExamOverviewJPanel;
import QuizSystem.entity.Exam;
import QuizSystem.utils.XDate;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author trant
 */
public class ExamsJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ExamsJDialog
     */
    ArrayList<Exam> listExams;
    ExamDAO examDAO = new ExamDAO();

    public ExamsJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        init();
    }

    public void init() {
        listExams = getExamFromDB();

        setLayout(listExams.size());
    }

    public void setLayout(int quantity) {
        int rows = quantity / 3;

        if (quantity <= 3) {
            panelExams.setLayout(new FlowLayout(FlowLayout.CENTER, 15, 15));
        } else {
            panelExams.setLayout(new GridLayout(quantity % 3 == 0 ? rows : rows + 1, 3, 15, 15));
        }

        for (int i = 0; i < quantity; i++) {
            Exam exam = listExams.get(i);
            ExamOverviewJPanel overview = new ExamOverviewJPanel();
            overview.setExamCode(exam.getMaDe());
            overview.getLbTitle().setText(exam.getTenDe());
            overview.getLbStartTime().setText("Bắt đầu: " + XDate.toString("hh:mm a - dd/MM/yyyy", exam.getThoiGianBatDau()));
            overview.getLbFinishTime().setText("Kết thúc: " + XDate.toString("hh:mm a - dd/MM/yyyy", exam.getThoiGianKetThuc()));
            overview.getLbQuantity().setText("Tổng số câu: " + String.valueOf(exam.getSoLuongCH()));
            overview.getLbDuration().setText("Thời gian: " + exam.getThoiLuong() + " phút");
            overview.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    ExamsJDialog.this.dispose();
                }
            });
            
            panelExams.add(overview);
        }
    }

    public ArrayList<Exam> getExamFromDB() {
        ArrayList<Exam> list = examDAO.selectAll();
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNguoiHoc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelExams = new javax.swing.JPanel();
        btnCreateExam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QuizSystem - Quản lý đề thi");
        setIconImage(new ImageIcon(getClass().getResource("/QuizSystem/icon/quiz-comic.png")).getImage());

        lbNguoiHoc.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        lbNguoiHoc.setForeground(new java.awt.Color(51, 204, 0));
        lbNguoiHoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNguoiHoc.setText("QUẢN LÝ ĐỀ THI");

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        jLabel1.setText("DANH SÁCH ĐỀ THI:");

        jScrollPane1.setAutoscrolls(true);

        javax.swing.GroupLayout panelExamsLayout = new javax.swing.GroupLayout(panelExams);
        panelExams.setLayout(panelExamsLayout);
        panelExamsLayout.setHorizontalGroup(
            panelExamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        panelExamsLayout.setVerticalGroup(
            panelExamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelExams);

        btnCreateExam.setBackground(new java.awt.Color(56, 170, 255));
        btnCreateExam.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnCreateExam.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/addition.png"))); // NOI18N
        btnCreateExam.setText("Tạo đề");
        btnCreateExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateExamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNguoiHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateExam)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNguoiHoc)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateExam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateExamActionPerformed
        new ExamDetailJDialog(null, true, null).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateExamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExamsJDialog dialog = new ExamsJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateExam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNguoiHoc;
    private javax.swing.JPanel panelExams;
    // End of variables declaration//GEN-END:variables
}
