/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package QuizSystem.ui;

import QuizSystem.dao.ExamDAO;
import QuizSystem.dao.ResultDAO;
import QuizSystem.entity.Result;
import QuizSystem.utils.AuthOfStudent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trant
 */
public class HistoryJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HistoryJDialog
     */
    ExamDAO examDAO = new ExamDAO();
    ResultDAO resultDAO = new ResultDAO();
    
    ArrayList<Result> listResults;
    
    public HistoryJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        init();
    }
    
    public void init() {
        listResults = this.getResultFromDB();
        
        lbMaSV.setText("Mã sinh viên: " + AuthOfStudent.student.getMaSV());
        lbTenSV.setText("Tên sinh viên: " + AuthOfStudent.student.getTenSV());
        
        fillToTable();
    }
    
    public ArrayList<Result> getResultFromDB() {
        ArrayList<Result> list = resultDAO.selectByMaSV(AuthOfStudent.student.getMaSV());
        return list;
    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tableHistory.getModel();
        model.setRowCount(0);
        
        for (Result result : listResults) {
            int quantity = examDAO.selectByID(result.getMaDe()).getSoLuongCH();
            model.addRow(new Object[] {result.getMaDe(), result.getTenDe(), result.getSoCauDung() +"/"+ quantity, result.getTongThoiGianThi(), result.getDiem()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNguoiHoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        lbMaSV = new javax.swing.JLabel();
        lbTenSV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QuizSystem - Lịch sử làm bài");
        setIconImage(new ImageIcon(getClass().getResource("/QuizSystem/icon/quiz-comic.png")).getImage());

        lbNguoiHoc.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        lbNguoiHoc.setForeground(new java.awt.Color(51, 204, 0));
        lbNguoiHoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNguoiHoc.setText("LỊCH SỬ LÀM BÀI");

        tableHistory.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đề", "Tên đề", "Số câu đúng", "Tổng thời gian (phút)", "Điểm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHistory.setRowHeight(30);
        jScrollPane1.setViewportView(tableHistory);

        lbMaSV.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lbMaSV.setForeground(new java.awt.Color(255, 51, 0));
        lbMaSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaSV.setText("Mã sinh viên: PS24687");

        lbTenSV.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lbTenSV.setForeground(new java.awt.Color(255, 51, 0));
        lbTenSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenSV.setText("Tên sinh viên: Trần Trung Thịnh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addComponent(lbNguoiHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNguoiHoc)
                .addGap(12, 12, 12)
                .addComponent(lbMaSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTenSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HistoryJDialog dialog = new HistoryJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaSV;
    private javax.swing.JLabel lbNguoiHoc;
    private javax.swing.JLabel lbTenSV;
    private javax.swing.JTable tableHistory;
    // End of variables declaration//GEN-END:variables
}
