/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizSystem.ui;

import QuizSystem.otherUI.QRCodeJDialog;
import QuizSystem.entity.Student;
import QuizSystem.utils.AuthOfStudent;
import QuizSystem.utils.MsgBox;
import QuizSystem.utils.XDate;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author trant
 */
public class MainStudentJFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentJFrame
     */
    public MainStudentJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        init();
    }

    public void init() {
        clock();
        lbInfo.setText(AuthOfStudent.getInfo());
    }

    public void logout() {
        AuthOfStudent.clear();
        this.dispose();
        new LoginJFrame().setVisible(true);
    }

    public void stop() {
        if (MsgBox.confirm(this, "Bạn chắc chắn muốn thoát?")) {
            System.exit(0);
        }
    }

    public void createQRCode() {
        Student student = AuthOfStudent.student;
        try {
            String account = student.getTaiKhoan().concat(" " + student.getMatKhau()).concat(" Sinh viên");
            String charset = "UTF-8";
            Map<EncodeHintType, ErrorCorrectionLevel> hinMap = new HashMap<>();
            hinMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
            BitMatrix matrix = new MultiFormatWriter().encode(new String(account.getBytes(charset), charset), BarcodeFormat.QR_CODE, 200, 200, hinMap);
            BufferedImage bufferedImage = MatrixToImageWriter.toBufferedImage(matrix);

            QRCodeJDialog qRCodeJDialog = new QRCodeJDialog(this, true);
            qRCodeJDialog.getLbQRCode().setIcon(new ImageIcon(bufferedImage));
            qRCodeJDialog.setVisible(true);

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void clock() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MainStudentJFrame.this.lbClock.setText(XDate.toString("hh:mm:ss a", new Date()));
            }
        });

        timer.start();
    }

    public void instructProduct() {
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (IOException e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnNewsFeed = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnIntroduce = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbInfo = new javax.swing.JLabel();
        lbClock = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemChangePass = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemGetQRCode = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        itemStop = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemNewsFeed = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemHistory = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemInstruction = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemIntroduce = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuizSystem - Sinh viên");
        setIconImage(new ImageIcon(getClass().getResource("/QuizSystem/icon/quiz-comic.png")).getImage());

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        btnLogout.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/log-out.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(80, 70));
        btnLogout.setPreferredSize(new java.awt.Dimension(80, 70));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnStop.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/stop.png"))); // NOI18N
        btnStop.setText("Kết thúc");
        btnStop.setFocusable(false);
        btnStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStop.setMaximumSize(new java.awt.Dimension(80, 70));
        btnStop.setPreferredSize(new java.awt.Dimension(80, 70));
        btnStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStop);
        jToolBar1.add(jSeparator1);

        btnNewsFeed.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnNewsFeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/news.png"))); // NOI18N
        btnNewsFeed.setText("Bài thi");
        btnNewsFeed.setFocusable(false);
        btnNewsFeed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewsFeed.setMaximumSize(new java.awt.Dimension(80, 70));
        btnNewsFeed.setPreferredSize(new java.awt.Dimension(80, 70));
        btnNewsFeed.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewsFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewsFeedActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewsFeed);

        btnHistory.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/history.png"))); // NOI18N
        btnHistory.setText("Lịch sử");
        btnHistory.setFocusable(false);
        btnHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistory.setMaximumSize(new java.awt.Dimension(80, 70));
        btnHistory.setPreferredSize(new java.awt.Dimension(80, 70));
        btnHistory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHistory);
        jToolBar1.add(jSeparator2);

        btnIntroduce.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        btnIntroduce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/introduce.png"))); // NOI18N
        btnIntroduce.setText("Sản phẩm");
        btnIntroduce.setFocusable(false);
        btnIntroduce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIntroduce.setMaximumSize(new java.awt.Dimension(80, 70));
        btnIntroduce.setPreferredSize(new java.awt.Dimension(80, 70));
        btnIntroduce.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIntroduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroduceActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIntroduce);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbInfo.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lbInfo.setText("Sinh viên: Trần Trung Thịnh");

        lbClock.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        lbClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/clock.png"))); // NOI18N
        lbClock.setText("00:00:00 AM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbClock)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbClock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/QuizzDe-logo-black.png"))); // NOI18N

        jMenu1.setText("Hệ thống");

        itemChangePass.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/exchange.png"))); // NOI18N
        itemChangePass.setText("Đổi mật khẩu");
        itemChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemChangePassActionPerformed(evt);
            }
        });
        jMenu1.add(itemChangePass);
        jMenu1.add(jSeparator3);

        itemGetQRCode.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemGetQRCode.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemGetQRCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/qr-code.png"))); // NOI18N
        itemGetQRCode.setText("Lấy QR Code");
        itemGetQRCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGetQRCodeActionPerformed(evt);
            }
        });
        jMenu1.add(itemGetQRCode);

        itemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemLogout.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/log-out.png"))); // NOI18N
        itemLogout.setText("Đăng xuất");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(itemLogout);

        itemStop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        itemStop.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/stop.png"))); // NOI18N
        itemStop.setText("Kết thúc");
        itemStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStopActionPerformed(evt);
            }
        });
        jMenu1.add(itemStop);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        itemNewsFeed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNewsFeed.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemNewsFeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/news.png"))); // NOI18N
        itemNewsFeed.setText("Bảng tin");
        itemNewsFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNewsFeedActionPerformed(evt);
            }
        });
        jMenu2.add(itemNewsFeed);
        jMenu2.add(jSeparator5);

        itemHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemHistory.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/history.png"))); // NOI18N
        itemHistory.setText("Lịch sử làm bài");
        itemHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistoryActionPerformed(evt);
            }
        });
        jMenu2.add(itemHistory);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Hỗ trợ");

        itemInstruction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        itemInstruction.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemInstruction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/instructions.png"))); // NOI18N
        itemInstruction.setText("Hướng dẫn sử dụng");
        itemInstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstructionActionPerformed(evt);
            }
        });
        jMenu4.add(itemInstruction);
        jMenu4.add(jSeparator4);

        itemIntroduce.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        itemIntroduce.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        itemIntroduce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizSystem/icon/introduce.png"))); // NOI18N
        itemIntroduce.setText("Giới thiệu sản phảm");
        itemIntroduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIntroduceActionPerformed(evt);
            }
        });
        jMenu4.add(itemIntroduce);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        this.stop();
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnNewsFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewsFeedActionPerformed
        new NewsFeedJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnNewsFeedActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        new HistoryJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnIntroduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroduceActionPerformed
        new IntroduceJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnIntroduceActionPerformed

    private void itemChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemChangePassActionPerformed
        new ChangePasswordJFrame().setVisible(true);
    }//GEN-LAST:event_itemChangePassActionPerformed

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        this.logout();
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void itemStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStopActionPerformed
        this.stop();
    }//GEN-LAST:event_itemStopActionPerformed

    private void itemNewsFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewsFeedActionPerformed
        new NewsFeedJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_itemNewsFeedActionPerformed

    private void itemHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistoryActionPerformed
        new HistoryJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_itemHistoryActionPerformed

    private void itemInstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstructionActionPerformed
        this.instructProduct();
    }//GEN-LAST:event_itemInstructionActionPerformed

    private void itemIntroduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIntroduceActionPerformed
        new IntroduceJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_itemIntroduceActionPerformed

    private void itemGetQRCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGetQRCodeActionPerformed
        this.createQRCode();
    }//GEN-LAST:event_itemGetQRCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainStudentJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainStudentJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainStudentJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStudentJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainStudentJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnIntroduce;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewsFeed;
    private javax.swing.JButton btnStop;
    private javax.swing.JMenuItem itemChangePass;
    private javax.swing.JMenuItem itemGetQRCode;
    private javax.swing.JMenuItem itemHistory;
    private javax.swing.JMenuItem itemInstruction;
    private javax.swing.JMenuItem itemIntroduce;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuItem itemNewsFeed;
    private javax.swing.JMenuItem itemStop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbClock;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbLogo;
    // End of variables declaration//GEN-END:variables
}
